package com.resourcegame.utils;

public enum MachineStatus {
    IDLE,
    WORKING,
    INVENTORY_FULL,
    INVENTORY_NEARLY_FULL,
    INSUFFICIENT_RESOURCES,
    NEEDS_CONFIG,
    NO_RESOURCES,
    NEEDS_MAINTENANCE,
    CONFIG_LIMIT_REACHED,
    MAINTENANCE_WARNING
}